version: '3.1'

services:
  db_postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: testdb
    ports:
      - 5432:5432

  db_mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: testdb
    ports:
      - 3306:3306
